# Run: golangci-lint run
# https://golangci-lint.run/usage/linters/
# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goimports
    - gofmt
    - gofumpt
    - goheader
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nestif
    - noctx
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
    - wsl

linters-settings:
  goimports:
    local-prefixes: github.com/dotzero/git-profile
  gomnd:
    settings:
      mnd:
        checks: condition,operation,return

issues:
  exclude-use-default: false
  exclude:
    - ST1000 # ST1000: at least one file in a package should have a package comment
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - funlen
        - gosec
